import type { PaymentGatewayConfig } from "@server/core/domain/payment_gateway/models/payment_gateway_config"
import { modelFactory } from "@turnkeyid/utils-ts"

export class DirectTransferConfig implements PaymentGatewayConfig {
  constructor(
    public merchant_id: string,
    public environment: string,
    public host: string,
    public additional_config: {
      payment_link_format: string;
    },
    public credentials = {},
    public admin_fee = 0,
    public host_secondary: string | undefined = void 0,
    public gateway_id = `DIRECT_BANK`,
  ) {}

  static factory = modelFactory(DirectTransferConfig, {
    autoGeneratedProp: [`gateway_id`, `credentials`, `admin_fee`, `host_secondary`],
  })
}
