import type { PaymentGatewayConfig } from "@server/core/domain/payment_gateway/models/payment_gateway_config"
import { modelFactory } from "@turnkeyid/utils-ts"

export class NusagateConfig implements PaymentGatewayConfig {
  constructor(
    public merchant_id: string,
    public credentials: NusagateCredentials,
    public environment: string,
    public host: string,
    public host_secondary?: string,
    public admin_fee = 0,
    public gateway_id = `NUSAGATE`,
    public additional_config?: {
      force_currency?: "ETH" | "BTC";
    },
  ) {}

  static factory = modelFactory(NusagateConfig, { autoGeneratedProp: [`gateway_id`] })
}

export type NusagateCredentials = {
  api_key: string;
  api_secret: string;
}
