// Generated by https://quicktype.io

export type NusagateInvoiceResponse = {
  data: Data;
  meta: Meta;
}

export type Data = {
  id: string;
  slug: string;
  type: string;
  externalId: string;
  description: string;
  dueDate: string;
  expiredAmountAt?: any;
  email: string;
  phoneNumber: string;
  payCurrency?: any;
  paymentLink: string;
  baseCurrency: string;
  price: number;
  amount?: any;
  paymentType: string;
  fee: number;
  paidAt?: any;
  completedAt?: any;
  details?: any;
  createdAt: string;
  updatedAt: string;
  status: string;
  merchant: {
    id: string;
    name: string;
  };
  paymentAddress?: any;
}

export type Meta = {
  message: string;
  statusCode: number;
}

