import { BaseAuth } from "@server/ui/server/middlewares/models/base_auth_payload"
import { modelFactory } from "@turnkeyid/utils-ts"

export class TransactionTokenPayload
  extends BaseAuth {
  constructor(
    public merchant_id: string,
    public transaction_id: string,
  ) {
    super()
  }

  static factory = modelFactory(TransactionTokenPayload, {
    autoGeneratedProp: [
      `environment`,
      `allow_origin`,
      `scope`,
    ],
  })
}
