import { modelFactory } from "@turnkeyid/utils-ts"
import type { PaymentGatewayConfig } from "@server/core/domain/payment_gateway/models/payment_gateway_config"

export class LinkQuConfig implements PaymentGatewayConfig {
  constructor(
    public merchant_id: string,
    public credentials: LinkQUCredentials,
    public environment: string,
    public host: string,
    public host_secondary?: string,
    public admin_fee = 0,
    public additional_config?: {
      partner_reff_code?: string;
      customer_name_code?: string;
    },
    public gateway_id = `LINKQU`,
  ) {}

  static factory = modelFactory(LinkQuConfig, { autoGeneratedProp: [`gateway_id`] })
}

export type LinkQUCredentials = {
  client_id: string;
  client_secret: string;
  pin: string;
  username: string;
}
