import { modelFactory, randomUUID } from "@commons"

export class Bank {
  constructor(
    public id: string = randomUUID(),
    public name: string,
    public code: string,
    public admin_fee: number = 0,
    public va_prefix: string | undefined = void 0,
    public status: string
  ) {}

  static factory = modelFactory(Bank, {
    autoGeneratedProp: [`id`, `admin_fee`, `va_prefix`],
  })
}
