import { createStringUnionType, modelFactory } from "@turnkeyid/utils-ts"

export const VirtualAccountStatus = [`OPEN`, `CLOSED`, `MAINTENANCE`] as const
export type VirtualAccountStatusType = typeof VirtualAccountStatus[number]
export const { getValidValue: getVirtualAccountStatusOption } =
  createStringUnionType(VirtualAccountStatus)

export class VirtualAccountDetail {
  constructor(
    public id: string,
    public name: string,
    public code: string,
    public admin_fee: number = 0,
    public va_prefix: string | undefined = void 0,
    public status: string,
    public bank_icon?: string
  ) {}

  static factory = modelFactory(VirtualAccountDetail, {
    autoGeneratedProp: [`admin_fee`, `va_prefix`],
  })
}
